### ISSUE TITLE
Select field definition:  inline grid editor renders HTML for selected option.

### ISSUE THREAD

**Issue by vmalyk** [pimcore/admin-ui-classic-bundle#1047]
If Select field definition configured  with Option Provider and it return HTML in Display Options  -  like it's provided for Workflow place provider:

<img width="1538" height="388" alt="Image" src="https://github.com/user-attachments/assets/61ddef36-32ea-42aa-bb3a-c73e696d6313" />

And adding this field to grid and use inline editor - after selection option contains HTML that shouldn't be and should be shown and work by the  same way as on Edit view. In video example how it works [here](https://www.dropbox.com/scl/fi/ush4t0waquzt8gyzfxs5b/Screen-Recording-2025-11-03-at-19.01.43.mov?rlkey=h1v3db86g96bzszbvf9vcpxf3&e=1&st=0ps2fkw7&dl=0).

Issue relevant for 2025.3 and latest Admin Classic UI from demo.pimcore.com.
The same behaviour on the Pimcore 11.5.11 and Admin Classic UI  1.7.13.

**Comment by robertSt7** [comment]
@vmalyk This bug is fixed here. Please update your instance https://github.com/pimcore/pimcore/pull/18270

**Comment by vmalyk** [comment]
@robertSt7 , 

Unf, cannot confirm as it's fixed in https://github.com/pimcore/pimcore/pull/18270. As You see, issue is still reproduced in 11.5.11, but fix was added in 11.5.6.  

i've researched and issue is related with configure Grid column editor - it reason of issue and Admin UI Classic bundle has this bug.  And if apply configuration and remove displayField: 'key' and specify tpl instead - editor works fine. If apply these change https://github.com/pimcore/admin-ui-classic-bundle/blob/2.3/public/js/pimcore/object/tags/select.js#L129-L142 and https://github.com/pimcore/admin-ui-classic-bundle/blob/2.3/public/js/pimcore/object/tags/select.js#L166-L178:

```
        editorConfig = Object.assign(editorConfig, {
            store: store,
            triggerAction: 'all',
            editable: false,
            mode: 'local',
            valueField: 'value',
            tpl: Ext.create('Ext.XTemplate',
                '<ul class="x-list-plain"><tpl for=".">',
                   '<li role="option" class="x-boundlist-item">{key}</li>',
               '</tpl></ul>'
            ),  
            displayTpl: Ext.create('Ext.XTemplate',
                '<tpl for=".">',
                '{[Ext.util.Format.stripTags(values.key)]}',
                '</tpl>'
            )
        });
```

Editor works fine in the Grid and for all Select-based fields. 
So, my suggestion, it's reopen ticket and verify issue again and might be apply suggested changes.

**Comment by robertSt7** [comment]
@vmalyk I have tried it to reproduce on the platform version 2024.4 and on demo.pimcore.com, but everything works on our side.

**Comment by vmalyk** [comment]
Hi @robertSt7 ,

I verified again on  2025.4 and the main difference is how configured Workflow that used for test previously. I setup as is for showing as bus still present on 2025.4 (btw, this version is set up) and on demo.pimcore.com.
Steps: 
1. Updated workflow product_data_enrichment and setup with type "Workflow" and change Marking Store to "Single State", set Field Name "Workflowstate"
2. Added  "Workflowstate" field to Car class and configured Options provider and Workflow product_data_enrichment.
3. Open Folder /upload/new.
4. Added "Workflowstate" Column to Grid.
5.  Try to change value in the grid - getting HTML in the selected value.

Sharing video with with showing all steps and confirm issue on the [current demo version](https://www.dropbox.com/scl/fi/tzsdkl7f9jcl6gj7xfhzq/Screen-Recording-2026-01-23-at-10.00.17.mov?rlkey=78iqh16mdmk1671pnrug7dws2&st=mdk62bsj&dl=0).

Some additional note, Workflow state it's 1 of example when Option provider return HTML in key and value. Issue will be the same if it'll be some custom Option Provider and return options with the same format.

FYI @fashxp

**Comment by kingjia90** [comment]
If i got correctly, you meant that it's showing raw html code BETWEEN after selection and before the unfocus the field to update/save (which correctly render the html), right?

Update: was able to reproduce, opened a  PR based on your suggestion https://github.com/pimcore/admin-ui-classic-bundle/pull/1083

**Comment by vmalyk** [comment]
@kingjia90 , 

thank for PR. One more thing, as will it be moved to 1.7 branch and Pimcore 11 support release?

**Comment by kingjia90** [comment]
Admin 1.7 along pimcore v11 are EOL and won't get any further release this year, unless there's something relevant for Pimcore LTS with hotfixes, eg. for security or data loss.

**Comment by vmalyk** [comment]
@kingjia90 ,

Thank you for details! As I see, Pimcore 2024.4 (as is 11.5) is LTS until December 2026: https://docs.pimcore.com/platform/Platform_Version/Platform_Version_Releases/ and if looking for this issue - it looks like hotfix and data loss fix. 
 
 
Might be based on that - this hotfix can be added to 1.7 regarding PR changes and time when this bug was reported - end on Autumn 2025? 🔢

**Comment by kingjia90** [comment]
Unfortunately, this appears to be only a visual/cosmetic bug based on my attempts to reproduce it, so it doesn’t qualify for the Pimcore LTS main or strict release criteria.

The issue isn’t related to the timing of when it was reported or merged, rather that there won’t be a release of `1.17.17` during the upcoming platform release (next week), and surely not in subsequent releases either (unless a critical security or data-loss hotfix necessitates one, and even if so, it would be in the private repository reserved to LTS subscribers). 

Given that, at this point, it's recommended to fork `1.7` or apply patches via git or composer.

**Comment by jdreesen** [comment]
I think you should add a note to https://docs.pimcore.com/platform/Platform_Version/Platform_Version_Releases/ that the LTS is enterprise only.

**Comment by kingjia90** [comment]
Thank you for your input!

The documentation you referenced is primarily aimed at developers and focuses on technical specifics. 
Broader, customer-facing clarifications were intended to be addressed by Partner Management, Sales or on the official website, which also helps avoid the need to synchronize information across multiple sources in case plan policies or rules change. 

That said, there is always room for improvement in terms of verbosity and explicitness, or simply links (which are missing, maybe also to avoid redirects/dead links 😅 ).

<img width="1320" height="617" alt="Image" src="https://github.com/user-attachments/assets/5e700057-2f77-4232-b89e-6756ded74169" />
https://pimcore.com/en/pricing

<img width="1305" height="427" alt="Image" src="https://github.com/user-attachments/assets/bcb453de-e8b3-445e-937e-4076fe95f0c6" />
https://pimcore.com/en/products/services/long-term-support

**Comment by jdreesen** [comment]
I think you should still add it. Most developers probably don't care about Partner Management or Sales and just look at the page I linked and then think that the LTS is available for the open code version.
